//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingStockVio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public string ApplicantName { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public string Responsible { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string Priority { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string AssignedEmployee { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ServiceCategories ServiceCategories { get; set; }
    }
}
