//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingStockVio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        public int ID { get; set; }
        public Nullable<int> ID_owner { get; set; }
        public Nullable<double> Water { get; set; }
        public Nullable<double> Electric_power { get; set; }
    
        public virtual Owners Owners { get; set; }
    }
}
