//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingStockVio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HousingStock : DbContext
    {
        public HousingStock()
            : base("name=HousingStock")
        {
        }
        public static HousingStock context;
        private static HousingStock GetContext()
        {
            if (context == null)
                context = new HousingStock();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Debt> Debt { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceCategories> ServiceCategories { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
