//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingStockVio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> ID_owner { get; set; }
        public string Period { get; set; }
        public Nullable<double> Accrued { get; set; }
        public Nullable<double> Paid_for { get; set; }
    
        public virtual Owners Owners { get; set; }
    }
}
